apiVersion: management.cattle.io/v3
kind: User
metadata:
  annotations:
    authz.management.cattle.io/creator-role-bindings: '{"created":["user"],"required":["user"]}'
    lifecycle.cattle.io/create.mgmt-auth-users-controller: "true"
  finalizers:
  - controller.cattle.io/mgmt-auth-users-controller
  labels:
    cattle.io/creator: norman
  name: u-testldap123
principalIds:
- openldap_user://cn=testldap123,ou=users,dc=example,dc=org
- local://u-testldap123
spec: {}
