apiVersion: management.cattle.io/v3
kind: GlobalRoleBinding
metadata:
  annotations:
    authz.management.cattle.io/crb-name: cattle-globalrolebinding-grb-testldap123
    cleanup.cattle.io/grbUpgradeCluster: "true"
    lifecycle.cattle.io/create.mgmt-auth-grb-controller: "true"
  finalizers:
  - controller.cattle.io/mgmt-auth-grb-controller
  labels:
    cattle.io/creator: norman
  name: grb-testldap123
  ownerReferences:
  - apiVersion: management.cattle.io/v3
    kind: GlobalRole
    name: user
    uid: d739ac42-7531-4e01-ba05-ce9983bd4e00
userName: u-testldap123
globalRoleName: user
