apiVersion: management.cattle.io/v3
kind: GlobalRoleBinding
metadata:
  annotations:
    authz.management.cattle.io/crb-name: cattle-globalrolebinding-grb-testldap123
    cleanup.cattle.io/grbUpgradeCluster: "true"
    lifecycle.cattle.io/create.mgmt-auth-grb-controller: "true"
  finalizers:
  - controller.cattle.io/mgmt-auth-grb-controller
  labels:
    cattle.io/creator: norman
  name: grb-testldap123
  userName: u-testldap123
globalRoleName: user
